//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGit
{
    using System;
    using System.Collections.Generic;
    
    public partial class predmet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public predmet()
        {
            this.profesors = new HashSet<profesors>();
        }
    
        public string naziv { get; set; }
        public string sifru { get; set; }
        public string kratak_opis { get; set; }
        public int godina { get; set; }
        public bool lab_vezbe { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<profesors> profesors { get; set; }
    }
}
