//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiGit
{
    using System;
    using System.Collections.Generic;
    
    public partial class students
    {
        public string ime { get; set; }
        public string srednje_ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public int br_indeksa { get; set; }
        public string jmbg { get; set; }
        public int id { get; set; }
    }
}
